---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fileshare
spec:
  rules:
  - host: s00000.k8s.slurm.io
    http:
      paths:
      - backend:
          serviceName: fileshare
          servicePort: 80
